"""
Django settings for riana project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7gem%2nl@o&_6k-^0hoq&881$v!f+*0(9^z1li0x3!0h9i&x0j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["147.52.71.221", "localhost", "192.168.1.23", "riana-hub.iesl.forth.gr"]

CSRF_TRUSTED_ORIGINS = [
    'https://riana.nffa-modeling.iesl.forth.gr',
]

# treat X-Forwarded-Proto: https as “this is secure”
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'riana',
    'widget_tweaks',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'riana.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'riana.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TEMPLATES[0]['DIRS'] = [BASE_DIR / 'riana' / 'templates']

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'calc'
LOGOUT_REDIRECT_URL = 'login'

# REST framework + JWT settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Use SMTP backend for real email delivery
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.iesl.forth.gr'        # e.g. 'smtp.gmail.com'
EMAIL_PORT = 25                       # or 465 for SSL
# EMAIL_USE_TLS = True                   # False if using SSL on 465
# EMAIL_USE_SSL = True                 # instead of USE_TLS if you prefer SSL

# Where to send contact‐form submissions
ADMIN_EMAIL = 'jsfakian@iesl.forth.gr'

EMAIL_HOST_USER = 'jsfakian@iesl.forth.gr'      # your SMTP login
EMAIL_HOST_PASSWORD = '8BGrJQx8pIA7'  # your SMTP password or app-specific token

DEFAULT_FROM_EMAIL = 'riana@iesl.forth.gr'
SERVER_EMAIL = DEFAULT_FROM_EMAIL      # sender address for error emails

# Optional: adjust timeout and connection reuse
EMAIL_TIMEOUT = 10                     # seconds
EMAIL_SSL_KEYFILE = None
EMAIL_SSL_CERTFILE = None

MEDIA_URL  = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Allow pages to be embedded in frames when served from the same origin
X_FRAME_OPTIONS = 'SAMEORIGIN'
